version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      #      KAFKA_ADVERTISED_HOST_NAME: localhost # TODO : 환경에 맞게 ip 변경 ex) 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # kafka가 zookeeper에 커넥션하기 위한 대상을 지정
      KAFKA_CREATE_TOPICS: |
      "start-searching":
        replication-factor :1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  spring-server:
    container_name: spring-server
    depends_on:
      - zookeeper
      - kafka
    image: suhwani/capstone:latest
    ports:
      - "8080:8080"
    build: .

  frontend:
    container_name: frontend
    depends_on:
      - spring-server
    image: suhwani/capstone_frontend:latest
    ports:
      - "80:80"
    build: .
